<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="APIAutomationRestAssured"
           tests="1"
           failures="1"
           errors="0"
           skipped="0"
           time="1.035">
    <properties></properties>

            <testcase
                name="testLoginVWO"
                time="1.035"
                classname="org.example.ddt.VwoExcel">

            <failure type="org.testng.internal.reflect.MethodMatcherException" message="
[public void org.example.ddt.VwoExcel.testLoginVWO()] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: testLoginVWO([])
Arguments: [(java.lang.String) hitanshu.developement@gmail.com,(java.lang.String) Qwerty@123]">
                <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void org.example.ddt.VwoExcel.testLoginVWO()] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: testLoginVWO([])
Arguments: [(java.lang.String) hitanshu.developement@gmail.com,(java.lang.String) Qwerty@123]
                org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:46)org.testng.internal.Parameters.injectParameters(Parameters.java:918)org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)java.base/java.util.ArrayList.forEach(ArrayList.java:1596)org.testng.TestRunner.privateRun(TestRunner.java:819)org.testng.TestRunner.run(TestRunner.java:619)org.testng.SuiteRunner.runTest(SuiteRunner.java:443)org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)org.testng.SuiteRunner.run(SuiteRunner.java:336)org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)org.testng.TestNG.runSuitesLocally(TestNG.java:1228)org.testng.TestNG.runSuites(TestNG.java:1134)org.testng.TestNG.run(TestNG.java:1101)com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </failure>
    </testcase>


</testsuite>
